### ISSUE TITLE
Support for landscape PDFs

### ISSUE THREAD

**Issue by luke-nehemedia** [spacecatninja/craft-imager-x-pdf-adapter#2]
First of all: I love your plugin. It works perfectly!

However, there is one thing I noticed: The images generated from a PDF that is in landscape format will always be in an upright, portrait image, which looks quite strange. 

Any way to fix this?

**Comment by aelvan** [comment]
Hi,

I just tested this with a PDF in landscape format, and it seems to work fine for me. Are you sure this is not just due to the transform being constrained by width/height or ratio? It could of course have something to do with the PDF and how it's encoded. If you don't figure it out, maybe you could send me a PDF that misbehaves so I can test with that. If it's not something that should be available publicly, please email to hi@spacecat.ninja.
